services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mypost
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    restart: always