services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  mock_api_b:
    image: mock_api_b:latest
    container_name: mock_api_b
    depends_on:
      - rabbitmq
    restart: always

  api_a:
    build:
      context: .
    container_name: api_a
    ports:
      - "8000:8000" 
    depends_on:
      - mock_api_b
      - rabbitmq
    restart: always

volumes:
  rabbitmq_data: